const q = (id, domain, difficulty, prompt, options, answer, rationale, context = "") => ({
  id,
  kind: id.startsWith("SYS") ? "systems" : "scenario",
  domain,
  difficulty,
  prompt,
  options,
  answer,
  rationale,
  context
});

export const systemsQuestions = [
  q("SYS-001", "Integration Strategy", "Foundation", "Which SAP Integration Suite capability is primarily used to design and run integration flows between applications?", ["Cloud Integration", "SAP Build Work Zone", "SAP Analytics Cloud", "SAP HANA Cloud"], 0, "Cloud Integration is the Integration Suite capability for modeling, deploying, and operating integration flows."),
  q("SYS-002", "Integration Strategy", "Foundation", "What is the main purpose of an integration flow, often called an iFlow?", ["To model the runtime processing of messages between sender and receiver systems", "To provision users in SAP Cloud Identity Services", "To create database calculation views", "To design Fiori launchpad pages"], 0, "An iFlow defines how a message enters, is processed, secured, transformed, routed, and delivered."),
  q("SYS-003", "Integration Strategy", "Intermediate", "Which principle best supports a clean-core integration strategy for SAP S/4HANA Cloud?", ["Use released APIs and side-by-side integration instead of modifying the core", "Place all integration logic inside custom database triggers", "Copy standard SAP code into a custom namespace", "Expose database tables directly to every consumer"], 0, "Released APIs and side-by-side extensions reduce modifications and make upgrades easier."),
  q("SYS-004", "Integration Strategy", "Intermediate", "What does SAP Integration Solution Advisory Methodology help an organization establish?", ["A governed integration strategy and technology-selection approach", "A replacement for every middleware product", "A password rotation schedule", "A transport request numbering scheme"], 0, "ISA-M provides guidance for defining integration domains, styles, technologies, and governance."),
  q("SYS-005", "Integration Strategy", "Intermediate", "Which pattern is most appropriate when a source should not wait for the target to finish processing?", ["Asynchronous messaging", "Synchronous request-reply", "Remote desktop access", "Direct database locking"], 0, "Asynchronous messaging decouples the sender from the receiver's processing time and availability."),
  q("SYS-006", "Integration Strategy", "Advanced", "Why should integration ownership and interface contracts be defined before implementation?", ["They clarify responsibilities, versioning, service levels, and change impact", "They remove the need for monitoring", "They guarantee that no mapping is required", "They make authentication optional"], 0, "Clear ownership and contracts are core governance controls for reliable enterprise integrations."),

  q("SYS-007", "Cloud Integration", "Foundation", "Which iFlow step can set or change a message body, header, or exchange property without scripting?", ["Content Modifier", "Gather", "Timer Start Event", "Data Store Sender"], 0, "A Content Modifier can create or update the body, headers, and exchange properties declaratively."),
  q("SYS-008", "Cloud Integration", "Foundation", "Which step evaluates conditions and sends a message down one of several branches?", ["Router", "Splitter", "Gather", "Message Mapping"], 0, "A Router evaluates expressions and chooses a route."),
  q("SYS-009", "Cloud Integration", "Foundation", "What is the purpose of a Message Mapping step?", ["Transform a source message structure into a target message structure", "Encrypt the tenant database", "Schedule an iFlow deployment", "Create an API product"], 0, "Message Mapping maps fields and structures from a source schema to a target schema."),
  q("SYS-010", "Cloud Integration", "Foundation", "Which pair of steps is commonly used to process repeating message elements separately and then recombine results?", ["Splitter and Gather", "Router and Timer", "Content Modifier and End Event", "Request Reply and Start Event"], 0, "A Splitter creates individual messages and a Gather can combine their results."),
  q("SYS-011", "Cloud Integration", "Intermediate", "What is an exchange property best suited for?", ["Holding internal processing data that should remain available across steps", "Sending every value as an HTTP response header", "Storing a password in plain text", "Creating a new tenant user"], 0, "Exchange properties are internal to message processing and are useful across multiple steps."),
  q("SYS-012", "Cloud Integration", "Intermediate", "What is a message header best suited for?", ["Carrying metadata that an adapter or receiver may need", "Storing long-term audit records", "Replacing all payload transformations", "Defining a user role collection"], 0, "Headers carry message metadata and can influence adapter or receiver behavior."),
  q("SYS-013", "Cloud Integration", "Intermediate", "Why use a Local Integration Process?", ["To encapsulate reusable logic inside the same iFlow", "To share logic with every tenant automatically", "To replace the sender adapter", "To create an API product"], 0, "A Local Integration Process organizes reusable processing logic within one iFlow."),
  q("SYS-014", "Cloud Integration", "Intermediate", "What does the ProcessDirect adapter enable?", ["Direct communication between deployed integration flows on the same tenant", "Direct SQL access to any on-premise database", "Browser access to the tenant keystore", "Transport of iFlows without deployment"], 0, "ProcessDirect is used for low-latency communication between iFlows on the same tenant."),
  q("SYS-015", "Cloud Integration", "Intermediate", "Which component is designed to catch errors raised inside its containing integration process?", ["Exception Subprocess", "Value Mapping", "Message Digest", "Number Range"], 0, "An Exception Subprocess handles exceptions raised in its process scope."),
  q("SYS-016", "Cloud Integration", "Intermediate", "What is the key benefit of externalized parameters?", ["Environment-specific values can be changed without remodeling the iFlow", "They automatically encrypt every payload", "They eliminate all transport work", "They convert synchronous calls to asynchronous calls"], 0, "Externalized parameters separate configurable environment values from the integration model."),
  q("SYS-017", "Cloud Integration", "Intermediate", "Which step calls a receiver and waits for its response before processing continues?", ["Request Reply", "Send", "Gather", "Persist"], 0, "Request Reply performs a synchronous call and continues with the returned response."),
  q("SYS-018", "Cloud Integration", "Intermediate", "Which step sends a message to a receiver without using the response in the remaining route?", ["Send", "Request Reply", "Message Mapping", "Router"], 0, "A Send step performs a one-way call from the perspective of the continuing flow."),
  q("SYS-019", "Cloud Integration", "Intermediate", "What problem does an Idempotent Process Call address?", ["Duplicate processing of messages identified by a key", "Invalid TLS certificates in a browser", "Missing API documentation", "Insufficient disk space in an ABAP system"], 0, "The idempotent pattern checks a message identifier so the same business event is not processed repeatedly."),
  q("SYS-020", "Cloud Integration", "Intermediate", "When is a Data Store useful in Cloud Integration?", ["When messages or state must be persisted for later processing", "When a browser theme must be saved", "When a role collection must be assigned", "When an API proxy needs a base path"], 0, "Data Stores persist message data that can be retrieved or consumed later."),
  q("SYS-021", "Cloud Integration", "Advanced", "What is the main architectural benefit of using a JMS queue between processing stages?", ["Durable asynchronous decoupling and controlled retries", "Automatic conversion of every payload to XML", "Removal of the need for authentication", "Direct editing of the target database"], 0, "JMS queues decouple producers and consumers and support resilient asynchronous processing."),
  q("SYS-022", "Cloud Integration", "Advanced", "Why should large payloads and long-running scripts be minimized in iFlows?", ["They consume tenant memory and processing resources and can reduce throughput", "They cause API products to become private", "They disable TLS automatically", "They prevent users from logging in"], 0, "Efficient payload handling and bounded scripts protect tenant performance and scalability."),
  q("SYS-023", "Cloud Integration", "Advanced", "What should a flow do when a receiver returns a transient server error?", ["Apply a bounded retry or queue-based retry strategy", "Retry forever without delay", "Discard the message immediately in every case", "Store the receiver password in the payload"], 0, "Transient failures should be retried with limits and delay to avoid message loss and retry storms."),
  q("SYS-024", "Cloud Integration", "Advanced", "Why is an explicit fallback branch valuable in a Router?", ["It handles messages that match none of the expected conditions", "It makes all conditions evaluate to true", "It encrypts the payload", "It redeploys the iFlow"], 0, "A default route prevents unmatched messages from being silently mishandled."),

  q("SYS-025", "Mapping & Transformation", "Foundation", "Which mapping option is most suitable for a declarative field-to-field XML transformation?", ["Message Mapping", "JMS Receiver", "Timer Start Event", "OAuth2 Credential"], 0, "Message Mapping provides graphical, schema-based transformation without custom code."),
  q("SYS-026", "Mapping & Transformation", "Foundation", "What is Value Mapping used for?", ["Translating equivalent business codes used by different systems", "Changing a user's password", "Monitoring API latency", "Creating an SFTP directory"], 0, "Value Mapping maintains correspondences such as company, country, or status codes across systems."),
  q("SYS-027", "Mapping & Transformation", "Intermediate", "When is XSLT Mapping a strong choice?", ["When transforming XML with rules naturally expressed in XSLT", "When storing OAuth client secrets", "When throttling an API", "When scheduling an integration"], 0, "XSLT is purpose-built for XML-to-XML transformations and structural rules."),
  q("SYS-028", "Mapping & Transformation", "Intermediate", "When is a Groovy Script justified in an iFlow?", ["When required logic cannot be expressed clearly with standard steps", "For every field copy in a simple mapping", "To store passwords in source code", "To replace monitoring"], 0, "Scripts are appropriate for specialized logic, while standard steps remain easier to maintain and govern."),
  q("SYS-029", "Mapping & Transformation", "Intermediate", "What is the safest way to build XML from untrusted text values in a script?", ["Use an XML builder or properly escape values", "Concatenate raw text directly into tags", "Remove all special characters", "Encode the complete document as a password"], 0, "Structured XML APIs or escaping prevent malformed XML and injection defects."),
  q("SYS-030", "Mapping & Transformation", "Intermediate", "Why are source and target schemas important in Message Mapping?", ["They define the structures and field paths available to the mapping", "They assign BTP role collections", "They configure TLS trust", "They create message processing logs"], 0, "Schemas describe the structures that the mapping consumes and produces."),
  q("SYS-031", "Mapping & Transformation", "Advanced", "What should be considered when mapping optional repeating source nodes to a mandatory target node?", ["Cardinality, defaulting, and the business rule for missing values", "Only the target file name", "The user's browser language", "The API product quota"], 0, "Cardinality and missing-value rules determine whether the target remains valid and meaningful."),
  q("SYS-032", "Mapping & Transformation", "Advanced", "Why preserve a correlation identifier during transformation?", ["It supports end-to-end tracking across systems and message formats", "It increases the payload size for its own sake", "It replaces receiver authentication", "It grants access to monitoring"], 0, "A stable correlation ID connects logs and business events across integration hops."),

  q("SYS-033", "Security", "Foundation", "Where should reusable usernames and passwords be stored for an iFlow?", ["Security Material", "A Content Modifier in plain text", "The message payload", "The iFlow description"], 0, "Security Material stores credentials centrally and avoids exposing secrets in models or payloads."),
  q("SYS-034", "Security", "Foundation", "What does TLS primarily protect for an HTTPS connection?", ["Data in transit and server authenticity", "Data stored in every backend table", "The correctness of message mapping", "The order of split messages"], 0, "TLS encrypts data in transit and uses certificates to establish identity and trust."),
  q("SYS-035", "Security", "Intermediate", "Which OAuth 2.0 grant is commonly used for machine-to-machine access without an end user?", ["Client Credentials", "Authorization Code with user consent only", "Implicit password sharing", "SAML logout"], 0, "Client Credentials is intended for service-to-service access using a client identity."),
  q("SYS-036", "Security", "Intermediate", "What is the role of the tenant keystore?", ["Manage keys and certificates used for encryption, signing, and TLS scenarios", "Store every message payload permanently", "Design API products", "Calculate exam scores"], 0, "The keystore holds cryptographic keys and certificates used by integrations."),
  q("SYS-037", "Security", "Intermediate", "Why should credentials be referenced by alias?", ["The iFlow can use centrally managed secrets without containing their values", "Aliases remove the need for authorization", "Aliases make passwords visible in logs", "Aliases convert certificates to JSON"], 0, "Credential aliases decouple secret values from integration content and simplify rotation."),
  q("SYS-038", "Security", "Intermediate", "What is principal propagation intended to preserve?", ["The identity of the original user across system boundaries", "The original XML namespace", "The original message size", "The original deployment version"], 0, "Principal propagation forwards the authenticated user identity to a trusted target."),
  q("SYS-039", "Security", "Advanced", "What should be done when a receiver certificate is renewed by a new issuing authority?", ["Update the relevant trust chain before the old chain expires", "Disable certificate validation", "Place the private key in the payload", "Switch the integration to HTTP"], 0, "Maintaining the correct trusted certificate chain prevents outages without weakening TLS validation."),
  q("SYS-040", "Security", "Advanced", "Which practice best reduces sensitive-data exposure during troubleshooting?", ["Mask sensitive fields and enable detailed tracing only for a limited period", "Write credentials into every log entry", "Keep trace enabled permanently", "Share message payloads through public links"], 0, "Targeted, time-limited diagnostics and data masking reduce the risk of exposing secrets or personal data."),

  q("SYS-041", "Connectivity & Adapters", "Foundation", "Which adapter is appropriate for exchanging files with an SFTP server?", ["SFTP", "OData", "JMS", "ProcessDirect"], 0, "The SFTP adapter reads and writes files over Secure File Transfer Protocol."),
  q("SYS-042", "Connectivity & Adapters", "Foundation", "Which component commonly provides a secure tunnel from SAP BTP to an on-premise system?", ["SAP Cloud Connector", "API product", "Message Mapping", "Data Store"], 0, "SAP Cloud Connector establishes controlled connectivity to on-premise resources without opening inbound firewall ports."),
  q("SYS-043", "Connectivity & Adapters", "Intermediate", "Which adapter is suitable for consuming or exposing OData services?", ["OData adapter", "SFTP adapter", "JMS adapter", "Mail adapter only"], 0, "OData adapters provide protocol-specific support for OData service interactions."),
  q("SYS-044", "Connectivity & Adapters", "Intermediate", "Which adapter is normally chosen for a SOAP web service with a WSDL contract?", ["SOAP adapter", "JMS adapter", "ProcessDirect adapter", "Data Store adapter"], 0, "The SOAP adapter supports SOAP message exchange based on web-service contracts."),
  q("SYS-045", "Connectivity & Adapters", "Intermediate", "What is a key use of the HTTP receiver adapter?", ["Calling REST-style or general HTTP endpoints", "Reading directly from a JMS queue", "Creating X.509 certificates", "Defining message mapping functions"], 0, "The HTTP receiver adapter invokes HTTP or REST endpoints with configurable methods, headers, and authentication."),
  q("SYS-046", "Connectivity & Adapters", "Advanced", "Which protocol family is commonly used for secure B2B document exchange with trading partners?", ["AS2 or AS4", "RDP", "IMAP only", "JDBC metadata"], 0, "AS2 and AS4 are established protocols for secure business-to-business message exchange."),
  q("SYS-047", "Connectivity & Adapters", "Advanced", "Why should receiver timeouts be configured deliberately?", ["They bound resource use and define when a slow call is treated as failed", "They guarantee the target always responds", "They replace retry design", "They encrypt messages"], 0, "Timeouts prevent calls from occupying resources indefinitely and are part of resilience design."),

  q("SYS-048", "Monitoring & Operations", "Foundation", "Where can an operator inspect the status of processed Cloud Integration messages?", ["Monitor Message Processing", "API Business Hub only", "The browser password manager", "SAP Build Apps"], 0, "Monitor Message Processing provides message status, timing, properties, and diagnostic information."),
  q("SYS-049", "Monitoring & Operations", "Foundation", "What does the Message Processing Log represent?", ["Runtime information for a processed message", "A list of all tenant passwords", "An API product subscription", "A source schema definition"], 0, "The MPL records runtime status and diagnostic metadata for message processing."),
  q("SYS-050", "Monitoring & Operations", "Intermediate", "When should trace mode be used?", ["Temporarily for focused troubleshooting because it can capture payload details and add overhead", "Permanently for every production message", "Only to assign user roles", "To create certificates"], 0, "Trace is powerful but should be time-limited due to data exposure and performance considerations."),
  q("SYS-051", "Monitoring & Operations", "Intermediate", "Which identifier is most useful for following one business transaction across multiple systems?", ["Correlation ID", "Tenant display name", "Browser session ID only", "CSS class name"], 0, "A correlation ID creates a shared tracking key across integration and application logs."),
  q("SYS-052", "Monitoring & Operations", "Advanced", "What should an alerting rule prioritize?", ["Actionable failures with business or service impact", "Every successful message", "Random payload fields", "Only the tenant logo"], 0, "Useful alerts are actionable, appropriately prioritized, and tied to operational impact."),
  q("SYS-053", "Monitoring & Operations", "Advanced", "Why should retry counts and dead-letter outcomes be monitored?", ["They reveal persistent target failures and messages requiring intervention", "They improve mapping automatically", "They rotate passwords", "They create new APIs"], 0, "Retries that exhaust their limit need operational visibility so messages are not silently stranded."),

  q("SYS-054", "API Management & Events", "Foundation", "What is an API proxy in SAP API Management?", ["A managed façade placed in front of a backend API", "A database backup", "An iFlow message mapping", "A BTP role collection"], 0, "An API proxy exposes a controlled endpoint while policies mediate access to the backend."),
  q("SYS-055", "API Management & Events", "Intermediate", "Which policy type protects a backend from sudden traffic bursts?", ["Spike Arrest", "Message Mapping", "Timer Start", "Value Mapping"], 0, "Spike Arrest smooths the rate of incoming calls to protect backend capacity."),
  q("SYS-056", "API Management & Events", "Intermediate", "What is the purpose of an API product?", ["Package APIs for discovery, access, and consumption by developers or applications", "Transform XML to JSON", "Store certificates", "Create an SFTP account"], 0, "API products group APIs and define how consumers discover and obtain access to them."),
  q("SYS-057", "API Management & Events", "Intermediate", "What is a core benefit of publish-subscribe messaging with SAP Event Mesh?", ["Publishers and subscribers are decoupled in time and implementation", "Every message becomes a synchronous API call", "All events are stored in an iFlow header", "Subscribers must share one password"], 0, "Publish-subscribe allows independent producers and consumers to evolve and operate asynchronously."),
  q("SYS-058", "API Management & Events", "Advanced", "What does Integration Advisor help create for B2B integration?", ["Message implementation guidelines and mapping guidelines", "BTP subaccounts", "Browser extensions", "ABAP transport requests"], 0, "Integration Advisor supports B2B message guideline and mapping artifact creation."),
  q("SYS-059", "API Management & Events", "Advanced", "Which governance concern is addressed by API versioning?", ["Allowing controlled evolution without unexpectedly breaking consumers", "Encrypting all database columns", "Removing the need for monitoring", "Making every endpoint public"], 0, "Versioning communicates and manages contract changes so consumers can migrate deliberately.")
];

export const scenarioQuestions = [
  q("SCN-001", "Integration Strategy", "Intermediate", "Which integration style should the architect recommend?", ["Publish an asynchronous employee event and let interested consumers subscribe", "Make each consumer poll the HR database every second", "Give all consumers direct write access to the HR tables", "Create one long synchronous chain through every target"], 0, "An event-driven publish-subscribe design decouples HR from multiple consumers and avoids a fragile synchronous chain.", "A company wants new-hire events from SuccessFactors to update identity, equipment, and payroll services. Each target has different availability and release cycles."),
  q("SCN-002", "Integration Strategy", "Intermediate", "What is the best first architecture action?", ["Define the interface contract, owner, service level, and change process", "Begin scripting before confirming the payload", "Expose the source database publicly", "Choose a protocol only because it was used on the last project"], 0, "A governed interface contract aligns business meaning, ownership, quality expectations, and change management.", "Two teams disagree about who owns a new order interface and how breaking changes will be communicated."),
  q("SCN-003", "Integration Strategy", "Advanced", "Which approach best supports clean core?", ["Consume the released S/4HANA API from a side-by-side integration", "Modify a standard S/4HANA table update program", "Read unreleased tables through a shared database user", "Copy standard function modules into custom code"], 0, "Released APIs and side-by-side integration preserve upgradeability and avoid core modifications.", "A project needs sales-order data from SAP S/4HANA Cloud for a logistics platform."),
  q("SCN-004", "Integration Strategy", "Intermediate", "Which pattern is most suitable?", ["Synchronous request-reply with a defined timeout and error response", "A nightly file regardless of urgency", "An event with no way to return the decision", "Manual re-entry by an operator"], 0, "A real-time eligibility decision needed before checkout completes is a synchronous request-reply use case.", "A web shop must confirm customer credit eligibility before allowing checkout to complete."),
  q("SCN-005", "Integration Strategy", "Advanced", "What should the integration architect introduce?", ["A canonical event contract and governed mapping at system boundaries", "One shared database schema for every application", "A rule that every application must use the source system's internal field names", "Separate undocumented point-to-point payloads for each new consumer"], 0, "A governed canonical contract reduces consumer coupling while mappings isolate system-specific models.", "Five applications represent a customer status with different codes and payload structures, and more consumers are expected."),
  q("SCN-006", "Integration Strategy", "Advanced", "What is the strongest recommendation?", ["Classify the interface in an integration strategy and select technology from agreed decision criteria", "Let each developer choose any tool without review", "Use synchronous integration for every requirement", "Mandate file transfer for all cloud APIs"], 0, "A documented strategy and selection method creates consistent, explainable technology choices.", "An enterprise uses several integration tools with overlapping capabilities and no consistent selection rules."),

  q("SCN-007", "Cloud Integration", "Foundation", "Which iFlow step should be used?", ["Router", "Gather", "Data Store Write", "Message Digest"], 0, "A Router evaluates the order value and sends the message to the matching branch.", "Orders above 50,000 must go through an approval endpoint; all other orders go directly to fulfillment."),
  q("SCN-008", "Cloud Integration", "Intermediate", "What should the developer use?", ["A Content Modifier with an expression that reads the incoming header", "A new API product", "A Data Store Sender adapter", "A Timer Start Event"], 0, "A Content Modifier can place incoming metadata into a header or exchange property without custom code.", "An incoming HTTP header named X-Correlation-ID must be retained in an exchange property for later logging."),
  q("SCN-009", "Cloud Integration", "Intermediate", "Which design is most appropriate?", ["Split the batch, process each item, and gather or summarize the results", "Send the complete batch repeatedly for every item", "Create 500 separate iFlows manually", "Store the batch in a credential artifact"], 0, "Splitter-based processing handles each repeating item while a later step can aggregate outcomes.", "A purchase-order batch contains up to 500 independent orders that require individual receiver calls."),
  q("SCN-010", "Cloud Integration", "Advanced", "How should the flow be redesigned?", ["Persist to JMS and consume with a separately scaled receiver flow", "Increase the synchronous timeout to several hours", "Retry continuously in a tight loop", "Remove all monitoring"], 0, "JMS decouples ingestion from the unstable receiver and enables controlled asynchronous retry.", "A synchronous product replication flow frequently times out because the receiver has unpredictable maintenance windows."),
  q("SCN-011", "Cloud Integration", "Intermediate", "What should the developer implement?", ["An Exception Subprocess that records context and routes the failure for handling", "A second sender adapter inside the same start event", "A hard-coded password in a script", "A Gather step before the error occurs"], 0, "An Exception Subprocess provides a controlled place to capture diagnostics and perform failure handling.", "Any runtime error in an invoice process must capture the invoice ID and notify the support route."),
  q("SCN-012", "Cloud Integration", "Advanced", "Which mechanism directly addresses the duplicate risk?", ["Idempotent Process Call using the shipment event ID", "A Timer Start Event", "A larger message body", "An API product quota"], 0, "An idempotent check keyed by the business event ID prevents the same shipment from being processed twice.", "A partner retries shipment notifications after network timeouts, and the target must never create a duplicate shipment."),
  q("SCN-013", "Cloud Integration", "Intermediate", "What is the most maintainable design?", ["Move the common steps to a Local Integration Process", "Copy the same steps into each branch", "Create a separate BTP subaccount for every branch", "Store the steps in a message header"], 0, "A Local Integration Process avoids duplication while keeping the logic inside the same iFlow.", "Three routes in one iFlow use the same validation and enrichment sequence."),
  q("SCN-014", "Cloud Integration", "Intermediate", "Which option should replace the duplicated HTTP calls?", ["A shared iFlow invoked through ProcessDirect", "A browser redirect", "A public database link", "A different password in every flow"], 0, "A shared ProcessDirect flow centralizes same-tenant logic and avoids repeated outbound calls.", "Several iFlows on the same tenant call identical reusable enrichment logic over HTTP."),
  q("SCN-015", "Cloud Integration", "Advanced", "What is the best configuration strategy?", ["Externalize the endpoint and credential alias and set environment values after transport", "Edit script source after every deployment", "Use one production endpoint in every environment", "Store the endpoint in the payload"], 0, "Externalized parameters make environment-specific configuration explicit and transport-friendly.", "The same package moves through development, test, and production, each with different receiver URLs and credential aliases."),
  q("SCN-016", "Cloud Integration", "Intermediate", "Which call pattern should be used?", ["Request Reply", "One-way Send", "Timer Start", "Data Store Sender"], 0, "Request Reply waits for the tax service result so later steps can use it.", "An order flow must call a tax service and use the returned amount in a subsequent mapping."),
  q("SCN-017", "Cloud Integration", "Advanced", "Which recovery design is strongest?", ["Write failures to a retry queue with bounded attempts and route exhausted messages to manual handling", "Retry forever with no delay", "Mark every failure as successful", "Delete the source event before processing"], 0, "Bounded retries handle transient faults while a terminal route keeps persistent failures visible and recoverable.", "A receiver returns HTTP 503 for short outages but occasionally rejects records permanently with HTTP 400."),
  q("SCN-018", "Cloud Integration", "Intermediate", "What should be added to the Router?", ["A default route that captures unknown countries for controlled handling", "A second start event", "An OAuth credential", "A Gather step"], 0, "A default route catches unexpected values and prevents messages from falling through without a defined outcome.", "A country-based Router has branches for DE, US, and ZA, but a message arrives for BR."),
  q("SCN-019", "Cloud Integration", "Advanced", "How can the order dependency be preserved?", ["Use sequential processing or a design that groups and orders events by business key", "Process all events in uncontrolled parallel threads", "Remove the order number", "Change all events into one large password"], 0, "Events sharing an order key need an ordering strategy so later states do not overtake earlier ones.", "Order status events for the same order must arrive at the target in sequence, while different orders may process concurrently."),
  q("SCN-020", "Cloud Integration", "Intermediate", "Which storage option is most appropriate?", ["Write the message to a Data Store and consume it with a scheduled Data Store sender flow", "Put the complete payload in an exchange property forever", "Store it in Security Material", "Create an API product"], 0, "A Data Store supports persisted handoff for later scheduled processing.", "A partner sends records throughout the day, but the target accepts a consolidated processing run each evening."),
  q("SCN-021", "Cloud Integration", "Advanced", "What should the developer change first?", ["Replace unnecessary script logic with standard streaming-friendly steps and avoid repeated payload copies", "Add more full-payload logs", "Convert every header into the body", "Enable trace permanently"], 0, "Reducing payload copies and preferring optimized standard steps lowers memory pressure for large messages.", "An iFlow handling 40 MB files repeatedly converts the body to strings in multiple scripts and has memory pressure."),
  q("SCN-022", "Cloud Integration", "Intermediate", "Which design gives the caller the expected outcome?", ["Handle the business exception and return a controlled error response with an appropriate status", "Return HTTP 200 with an empty body for every failure", "Wait until the caller times out", "Write the error only to a local browser console"], 0, "A synchronous API should return a clear, intentional status and response contract for known business errors.", "A synchronous customer API must tell callers when a customer number is invalid."),
  q("SCN-023", "Cloud Integration", "Advanced", "How should the maintenance flow identify records safely?", ["Persist a stable business key and processing status, then select only eligible records", "Select records by display order only", "Use the current browser time as the only key", "Delete every record before reading it"], 0, "Stable keys and explicit status support repeatable, restartable batch processing.", "A nightly flow resumes after failure and must avoid reprocessing records that already completed."),
  q("SCN-024", "Cloud Integration", "Intermediate", "What is the clearest model?", ["Use a Multicast to invoke independent branches, then join only if the flow needs their combined completion", "Chain the unrelated calls only because one line is easier to draw", "Duplicate the sender message manually", "Store all receiver URLs in a password"], 0, "A Multicast expresses independent branches; joining is required only when downstream logic depends on their completion.", "A message must independently notify an archive service and an analytics service after core processing."),

  q("SCN-025", "Mapping & Transformation", "Foundation", "Which artifact should be used?", ["Value Mapping", "Security Material", "JMS Queue", "API Product"], 0, "Value Mapping stores equivalent business codes across systems.", "The source uses country code UK while the target requires GB, with similar differences for many countries."),
  q("SCN-026", "Mapping & Transformation", "Intermediate", "Which transformation approach is a strong fit?", ["XSLT Mapping", "Timer Start Event", "OAuth client credentials", "Spike Arrest"], 0, "XSLT is well suited to structural XML transformations such as grouping and element reorganization.", "An XML payload must be reorganized, namespaces changed, and line items grouped by product category."),
  q("SCN-027", "Mapping & Transformation", "Intermediate", "What should the mapping include?", ["An explicit default or error rule for a missing optional source value", "A hard-coded receiver password", "A permanent trace setting", "An unrelated API quota"], 0, "The mapping must define how an optional source value satisfies a mandatory target requirement.", "A target field is mandatory, but the corresponding source field is optional for legacy records."),
  q("SCN-028", "Mapping & Transformation", "Advanced", "What is the safest implementation?", ["Parse JSON, create XML with a structured builder, and validate the result", "Concatenate raw customer text between XML tags", "Remove all punctuation from customer names", "Store the JSON in a certificate"], 0, "Parsing and structured XML generation correctly escape data and produce valid output.", "A custom transformation must convert customer-supplied JSON text to XML, including names containing ampersands."),
  q("SCN-029", "Mapping & Transformation", "Intermediate", "Which mapping design is best?", ["Map the first available phone number and define a clear fallback when none exists", "Assume the first phone element always exists", "Create a new API product for each phone", "Fail every record with more than one phone"], 0, "The mapping should account for optional, repeating source data and an explicit no-value outcome.", "A source can contain zero to five phone numbers, while the target accepts one preferred number."),
  q("SCN-030", "Mapping & Transformation", "Advanced", "What should be preserved outside the business payload?", ["The original correlation ID in a header or property", "The full credential secret", "The user's browser history", "The tenant private key"], 0, "Keeping correlation metadata separate allows formats to change while end-to-end tracking remains stable.", "A JSON-to-XML transformation replaces the full body, but operations still needs the original transaction identifier."),
  q("SCN-031", "Mapping & Transformation", "Intermediate", "Which approach is most maintainable?", ["Use Message Mapping with the source and target schemas", "Write a long script of string replacements", "Edit the target database directly", "Create a separate user for every field"], 0, "A schema-driven Message Mapping makes a straightforward field mapping visible and maintainable.", "A purchase-order XML requires mostly direct field mappings plus a few simple constants."),
  q("SCN-032", "Mapping & Transformation", "Advanced", "How should the team reduce mapping defects?", ["Add representative samples, boundary cases, and schema validation to automated tests", "Test only one perfect message manually", "Disable schema checks", "Use production as the first test environment"], 0, "Automated mapping tests with realistic and edge-case payloads catch structural and business-rule defects early.", "A complex message mapping changes frequently and regressions are discovered only after deployment."),

  q("SCN-033", "Security", "Foundation", "Where should the password be moved?", ["A User Credentials artifact in Security Material referenced by alias", "A message header logged on every call", "A comment in the iFlow", "A public source repository"], 0, "Security Material centralizes secret storage and allows the iFlow to reference an alias."),
  q("SCN-034", "Security", "Intermediate", "Which OAuth configuration is most appropriate?", ["Client Credentials with the required scope stored in an OAuth credential artifact", "Authorization Code requiring an employee to sign in for every batch", "A password placed in the query string", "No authentication because both systems are cloud based"], 0, "A scheduled service-to-service call normally uses Client Credentials and least-privilege scopes.", "A nightly unattended iFlow calls a protected API that supports OAuth 2.0 and does not act for a user."),
  q("SCN-035", "Security", "Advanced", "What should operations do before the change?", ["Import the new trust chain, test connectivity, and keep overlap until cutover", "Disable hostname verification", "Switch to HTTP", "Ask the partner for its private key"], 0, "Updating and testing trust before cutover prevents an outage while preserving TLS security.", "A partner announces that its HTTPS certificate chain will change next month."),
  q("SCN-036", "Security", "Intermediate", "Which solution fits the requirement?", ["Principal propagation through a trusted connectivity setup", "One shared technical account for all users", "The user's password copied into the payload", "Anonymous access"], 0, "Principal propagation preserves end-user identity so the target can authorize and audit that user.", "An employee-facing application calls an on-premise SAP system, which must authorize the original employee rather than a shared technical user."),
  q("SCN-037", "Security", "Advanced", "What should be changed?", ["Mask or remove sensitive fields and use time-limited targeted trace", "Keep full trace forever for convenience", "Email payloads to the whole team", "Put the values into the URL"], 0, "Sensitive values should be minimized in logs, masked, and captured only under controlled troubleshooting windows.", "Production traces reveal bank account and national ID values during support investigations."),
  q("SCN-038", "Security", "Intermediate", "What is the correct connection design?", ["Use SAP Cloud Connector with a narrowly exposed virtual host and resource path", "Open the internal host directly to the public internet", "Place the database password in JavaScript", "Disable the corporate firewall"], 0, "Cloud Connector provides controlled outbound-established access and limits which internal resources are exposed."),
  q("SCN-039", "Security", "Advanced", "Which control best enforces least privilege?", ["Issue separate client credentials with only the scopes each consumer needs", "Give every application the administrator scope", "Share one root credential", "Put authorization decisions in a CSS file"], 0, "Per-client, least-privilege scopes limit impact and support independent revocation and audit."),
  q("SCN-040", "Security", "Intermediate", "What must be available to sign the outbound payload?", ["The sender's private key and certificate in the keystore", "Only the receiver's public certificate", "A Data Store entry", "An API product"], 0, "Digital signing uses the sender's private key; the receiver verifies with the corresponding public certificate.", "A partner requires XML messages to be digitally signed so it can verify origin and integrity."),

  q("SCN-041", "Connectivity & Adapters", "Foundation", "Which adapter and authentication are appropriate?", ["SFTP with SSH key or managed credential authentication", "HTTP without TLS", "JMS with a browser cookie", "ProcessDirect across unrelated tenants"], 0, "SFTP supports secure file exchange and should use managed credentials or keys.", "A bank drops encrypted settlement files on a secure file server every hour."),
  q("SCN-042", "Connectivity & Adapters", "Intermediate", "Which adapter should the flow use?", ["SOAP receiver adapter configured from the service contract", "Data Store Sender", "JMS sender only", "Timer receiver"], 0, "A SOAP adapter is designed for WSDL-based SOAP service invocation.", "A legacy target exposes a WSDL-based service and expects SOAP headers and a signed request."),
  q("SCN-043", "Connectivity & Adapters", "Intermediate", "What should be configured deliberately?", ["HTTP method, content type, authentication, timeout, and response handling", "Only the endpoint color", "A database trigger in the target", "A new tenant for each call"], 0, "A robust HTTP receiver configuration defines the full request contract and failure behavior.", "An iFlow calls a REST endpoint to create cases and must interpret both success and error responses."),
  q("SCN-044", "Connectivity & Adapters", "Advanced", "Which design is most appropriate?", ["Use an OData adapter with paging and selective query options", "Request the complete entity set every minute", "Use SFTP because the source supports OData", "Place all rows in a URL header"], 0, "Paging and selective OData queries control payload size and load for large entity sets.", "An OData service contains millions of records, but the integration needs only records changed since the last run."),
  q("SCN-045", "Connectivity & Adapters", "Advanced", "What should be considered first?", ["An AS2 or AS4 B2B channel with partner certificates and delivery evidence", "A public unauthenticated HTTP endpoint", "A shared spreadsheet", "A browser extension"], 0, "AS2 or AS4 provides secure partner exchange patterns, signatures, encryption, and delivery handling.", "A trading partner requires signed and encrypted business documents with non-repudiation-style delivery evidence."),
  q("SCN-046", "Connectivity & Adapters", "Intermediate", "How should the timeout be handled?", ["Set a timeout aligned to the service level and route timeout failures into the retry strategy", "Leave the call open indefinitely", "Retry immediately forever", "Disable error handling"], 0, "A deliberate timeout and bounded recovery policy protect resources and define predictable behavior.", "A receiver normally responds in two seconds but can hang during outages."),
  q("SCN-047", "Connectivity & Adapters", "Advanced", "Which approach reduces data loss during temporary target outages?", ["Receive to a durable JMS queue and let a consumer deliver when the target recovers", "Keep every sender connection open", "Reject all messages without logging", "Store messages in the credential vault"], 0, "A durable queue acknowledges intake independently and allows later delivery after target recovery.", "A high-volume source cannot resend events, while the target occasionally goes offline for 20 minutes."),

  q("SCN-048", "Monitoring & Operations", "Foundation", "Where should support investigate first?", ["Monitor Message Processing and inspect the failed message details", "The API product catalog", "The browser theme settings", "The source code repository's README only"], 0, "Message monitoring provides the status, failure step, timestamps, and available diagnostic context."),
  q("SCN-049", "Monitoring & Operations", "Intermediate", "What is the most useful operational improvement?", ["Carry the business order ID as a searchable correlation property and structured log field", "Log only a random internal ID", "Enable full trace for every message forever", "Remove all identifiers"], 0, "A business correlation key helps support find the same transaction across systems quickly.", "Support receives incidents by order number but can search the tenant only by technical message ID."),
  q("SCN-050", "Monitoring & Operations", "Advanced", "How should alerting be redesigned?", ["Alert on actionable failures, sustained retry growth, and service-level breaches with deduplication", "Send an alert for every successful message", "Disable all alerts", "Alert only once per month"], 0, "Actionable, deduplicated alerts detect real impact without overwhelming responders."),
  q("SCN-051", "Monitoring & Operations", "Intermediate", "What is the safest diagnostic action?", ["Enable trace briefly for a reproducible test message, then disable it and protect captured data", "Enable trace permanently in production", "Publish the trace online", "Store credentials in the payload to make debugging easier"], 0, "Time-limited targeted trace balances diagnostic value with performance and privacy risk.", "A mapping defect cannot be reproduced from normal log metadata and the payload must be inspected."),
  q("SCN-052", "Monitoring & Operations", "Advanced", "What should the operations dashboard expose?", ["Queue depth, oldest message age, retry count, and dead-letter volume", "Only the tenant logo", "The developers' browser versions", "Every successful payload in full"], 0, "Queue health metrics reveal backlog, delay, retry pressure, and terminal failures."),
  q("SCN-053", "Monitoring & Operations", "Advanced", "Which response is appropriate?", ["Stop or contain the retry source, correct the configuration, and reprocess only validated failed messages", "Let retries continue at maximum speed", "Delete all message logs", "Disable target authentication"], 0, "Containment prevents further load, while controlled correction and replay protect data consistency.", "A credential error causes thousands of messages to retry and increases load on the receiver."),

  q("SCN-054", "API Management & Events", "Foundation", "What should be placed in front of the backend?", ["An API proxy with authentication and traffic-management policies", "A public database account", "A Data Store Sender", "An XSLT stylesheet only"], 0, "API Management provides a controlled façade with security, mediation, analytics, and traffic policies.", "A mobile application needs a stable public endpoint for an internal customer API."),
  q("SCN-055", "API Management & Events", "Intermediate", "Which policy combination is most relevant?", ["Spike Arrest for burst smoothing and Quota for consumption limits", "Message Mapping and Gather", "Timer and Data Store", "XSLT and SFTP"], 0, "Spike Arrest controls short-term rate while Quota governs allowed consumption over a period.", "A partner API must allow 10,000 calls per day but protect the backend from sudden bursts."),
  q("SCN-056", "API Management & Events", "Intermediate", "How should access be packaged?", ["Publish the relevant proxies in an API product and approve application access", "Share the backend administrator password", "Expose every internal API automatically", "Put access rules in the response body"], 0, "API products package approved APIs for discoverable, governed application consumption.", "External developers should discover two approved APIs and request credentials for their registered applications."),
  q("SCN-057", "API Management & Events", "Advanced", "Which pattern best fits?", ["Publish the business event to Event Mesh and let each consumer subscribe independently", "Call every consumer synchronously from the sales transaction", "Give consumers direct access to the sales database", "Send one email containing the raw database row"], 0, "Event Mesh decouples the publisher from multiple independently operated consumers.", "When an order is confirmed, analytics, warehouse, and customer-notification services all need the event."),
  q("SCN-058", "API Management & Events", "Advanced", "Which Integration Advisor artifacts should the team create?", ["A message implementation guideline and mapping guideline", "A new BTP global account", "A browser bookmark and CSS theme", "An API quota and timer"], 0, "Integration Advisor uses message implementation and mapping guidelines to define partner-specific B2B structures and transformations.", "A manufacturer must onboard many partners that use different subsets and code conventions of the same industry message standard."),
  q("SCN-059", "API Management & Events", "Advanced", "What is the safest evolution strategy?", ["Release a new API version, document the contract change, and run a managed consumer migration", "Change the existing response without notice", "Keep one version but return random fields", "Give consumers direct database access"], 0, "Versioned, documented evolution protects current consumers while enabling a controlled migration.", "A public API must replace a field and change validation rules, but several consumers cannot upgrade immediately.")
];

export const allQuestions = [...systemsQuestions, ...scenarioQuestions];

export const domainOrder = [
  "Integration Strategy",
  "Cloud Integration",
  "Mapping & Transformation",
  "Security",
  "Connectivity & Adapters",
  "Monitoring & Operations",
  "API Management & Events"
];

export function questionById(id) {
  return allQuestions.find((question) => question.id === id);
}
